export interface HardcodedFood {
  name: string;
  names: string[];
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  default_weight_g: number;
  portion: string;
}

export const HARDCODED_FOODS: HardcodedFood[] = [
  {
    name: "Pechuga de pollo",
    names: ["pechuga de pollo", "pollo", "pechuga pollo", "pollo pechuga"],
    kcal: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    default_weight_g: 150,
    portion: "1 pechuga mediana (~150g)",
  },
  {
    name: "Huevo",
    names: ["huevo", "huevos", "huevo revuelto"],
    kcal: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    default_weight_g: 60,
    portion: "1 huevo grande (~60g)",
  },
  {
    name: "Pan integral",
    names: ["pan integral", "pan", "tostada integral"],
    kcal: 247,
    protein: 9,
    carbs: 41,
    fat: 3.4,
    fiber: 7,
    default_weight_g: 40,
    portion: "1 rebanada (~40g)",
  },
  {
    name: "Quinoa cocida",
    names: ["quinoa", "quinoa cocida", "quimua"],
    kcal: 130,
    protein: 4.4,
    carbs: 23.7,
    fat: 1.9,
    fiber: 2.8,
    default_weight_g: 185,
    portion: "1 ración cocida (~185g)",
  },
  {
    name: "Pimiento rojo",
    names: ["pimiento", "pimiento rojo", "pimiento asado"],
    kcal: 31,
    protein: 1,
    carbs: 7,
    fat: 0.3,
    fiber: 1.7,
    default_weight_g: 120,
    portion: "1 pimiento mediano (~120g)",
  },
  {
    name: "Cereza",
    names: ["cereza", "cerezas"],
    kcal: 63,
    protein: 1.1,
    carbs: 16,
    fat: 0.2,
    fiber: 2.1,
    default_weight_g: 100,
    portion: "1 puñado (~100g)",
  },
  {
    name: "Uva verde",
    names: ["uva", "uva verde", "uvas"],
    kcal: 70,
    protein: 0.7,
    carbs: 18,
    fat: 0.4,
    fiber: 0.9,
    default_weight_g: 100,
    portion: "1 racimo pequeño (~100g)",
  },
  {
    name: "Yogur natural 0%",
    names: ["yogur", "yogur natural", "yogur griego", "stracciatella"],
    kcal: 59,
    protein: 10,
    carbs: 3.3,
    fat: 0.5,
    fiber: 0,
    default_weight_g: 125,
    portion: "1 yogur (~125g)",
  },
  {
    name: "Queso Manchego",
    names: ["queso manchego", "queso", "manchego"],
    kcal: 424,
    protein: 28,
    carbs: 1.3,
    fat: 35,
    fiber: 0,
    default_weight_g: 30,
    portion: "1 loncha (~30g)",
  },
  {
    name: "Plátano",
    names: ["platano", "banana", "platano maduro"],
    kcal: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    default_weight_g: 120,
    portion: "1 plátano mediano (~120g)",
  },
  {
    name: "Atún en lata",
    names: ["atun", "atun en lata", "atun en agua"],
    kcal: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    fiber: 0,
    default_weight_g: 80,
    portion: "1 lata escurrida (~80g)",
  },
  {
    name: "Espinaca",
    names: ["espinaca", "espinacas", "spinach"],
    kcal: 23,
    protein: 2.7,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    default_weight_g: 60,
    portion: "1 puñado crudo (~60g)",
  },
  {
    name: "Tomate",
    names: ["tomate", "tomate cherry", "tomates"],
    kcal: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    default_weight_g: 120,
    portion: "1 tomate mediano (~120g)",
  },
  {
    name: "Pepino",
    names: ["pepino", "pepinos"],
    kcal: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    default_weight_g: 100,
    portion: "medio pepino (~100g)",
  },
  {
    name: "Maíz en lata",
    names: ["maiz", "maiz en lata", "choclo"],
    kcal: 76,
    protein: 2.7,
    carbs: 17,
    fat: 0.6,
    fiber: 2,
    default_weight_g: 80,
    portion: "1 ración (~80g)",
  },
  {
    name: "Avena",
    names: ["avena", "copos de avena", "oatmeal"],
    kcal: 379,
    protein: 13,
    carbs: 68,
    fat: 7,
    fiber: 10,
    default_weight_g: 40,
    portion: "1 ración seca (~40g)",
  },
  {
    name: "Brócoli",
    names: ["brocoli", "brocoli al vapor", "broccoli"],
    kcal: 35,
    protein: 2.4,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    default_weight_g: 150,
    portion: "1 ración al vapor (~150g)",
  },
  {
    name: "Aceite de oliva",
    names: ["aceite", "aceite de oliva"],
    kcal: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    default_weight_g: 10,
    portion: "1 cucharada (~10g)",
  },
  {
    name: "Leche de soja",
    names: ["leche de soja", "soy milk", "leche soja"],
    kcal: 40,
    protein: 3.3,
    carbs: 1.9,
    fat: 1.9,
    fiber: 0.5,
    default_weight_g: 240,
    portion: "1 vaso (~240ml)",
  },
  {
    name: "Pan de sourdough",
    names: ["pan sourdough", "sourdough", "pan masa madre"],
    kcal: 250,
    protein: 9,
    carbs: 47,
    fat: 2,
    fiber: 3,
    default_weight_g: 50,
    portion: "1 rebanada gruesa (~50g)",
  },
];
